### ISSUE TITLE
Absolutely fantastic job! Thank you :)

### ISSUE THREAD

**Issue by asigalov61** [andfanilo/writing-with-gpt2#2]
Hey Fanilo,

I just wanted to say hi and I wanted to thank you for your amazing and brilliant creation/repo/code. I am very impressed and I will be seriously looking forward to trying out your implementation for my needs.

I also wanted to ask you if you think it is possible to somehow make your solution compatible with say frameworks so that it is not mode-specific architecture-dependent? 

There is a HUGE need right now for many DL/ML researchers and users for an easy, compatible, and smart solution to put DL/ML models online, so I was wondering what you think about it and if you plan/want to do something like that in the future?

I only have 2 GPT2 projects, so it would only work for these projects. But I would love to see all of my projects online. In fact, I would be willing to pay any reasonable/fair price for implementation/service like that.

Anyways, let me know if possible what you think

Most sincerely,

Aleksandr Sigalov

**Comment by andfanilo** [comment]
Hi @asigalov61, thanks for the compliments :) this prototype was actually created for a paid gig and the user kindly accepted that I release a big part of it as open source so others benefit from it!

For deployment purposes, I usually recommend data scientists to use [Streamlit](https://www.streamlit.io/) + [Streamlit Sharing](https://blog.streamlit.io/introducing-streamlit-sharing/) to deploy their models (disclaimer: I'm a Streamlit Community Moderator). Is it something you had considered ?

For this project, user wanted a text editor with suggestions coming from GPT-2, and while we have a [Quill component for Streamlit](https://discuss.streamlit.io/t/quill-editor/5761) I think coming back and forth between Streamlit Python and Quill would be costly, so we decided instead to put GPT-2 in [FastAPI](https://fastapi.tiangolo.com/) and build a quick React frontend to communicate with the API.

> I also wanted to ask you if you think it is possible to somehow make your solution compatible with say frameworks so that it is not mode-specific architecture-dependent?

I did not really plan for that, this repo really is a oneshot, but I think you can pretty much fork the project and put your GPT-2 code inside `backend/app.py` instead.

Otherwise for a quick paid prototype for deploying your GPT-2 models we can discuss that offline ;) my contact should be in my profile.

Best,
Fanilo

**Comment by asigalov61** [comment]
Thank you for your friendly and prompt reply.  And thank you very much for your clear response and suggestions. I value this a lot.

Nice to meet a Streamlit mod 🙂 You guys did a great job with Streamlit. I actually signed up for Streamlit invite and I am waiting for a response. However, it was not very clear to me if Streamlit offers streamlined (pun is not intended) functionality and user-level deployment services. If you can elaborate/explain to me how a GPT2 model can be deployed w/o coding/dealing with API/Java, I will really appreciate it.

And I am actually happy that your open-source implementation is based on FastAI because I really do not like dealing with proprietary or difficult to use the software.

I will send you a PM shortly because I would be extremely interested in hiring you to create a demo/prototype for me. I need most basic implementation and I am willing to pay any reasonable and fair price for a job well done within a deadline.

Thank you again.

Alex
________________________________

**Comment by asigalov61** [comment]
Actually, can you please contact me directly. You do not have a pub email and I do not use social networks so I can't send you a PM.

Thanks and stay well and safe.

asigalov61@hotmail.com/gmail.com
________________________________

**Comment by asigalov61** [comment]
@andfanilo
